[package]
name = "nom-obj"
version = "0.1.1"
authors = ["dwerner <dan.werner@gmail.com>"]
license = "BSD"
description = "A simple obj/mtl parser written with nom."

[dependencies.nom]
version = "^2.2"
